In [3]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("/diabetes.csv")

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [10]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

**Finding the Correlation of all column in Dataframe**

In [11]:
df.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Outcome                      0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221071                  0.137337   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.436783  0.392573                  0.183928   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.042163  0.036242                  0.033561   
Outcome                   0.130548  0.292695                  0.173844   

                               Age   Outcome  
Pregnancies               0.544341  0.221898  
Glucose                   0.263514  0.466581  
BloodPressure             0.239528  0.065068  
SkinThickness            -0.113970  0.074752  
Insulin                  -0.042163  0.130548  
BMI                       0.036242  0.292695  
DiabetesPedigreeFunction  0.033561  0.173844  
Age                       1.000000  0.238356  
Outcome                   0.238356  1.000000

In [12]:
x=df[["Glucose","BMI","Age","Pregnancies","DiabetesPedigreeFunction","Insulin"]].values

In [13]:
x

array([[148.   ,  33.6  ,  50.   ,   6.   ,   0.627,   0.   ],
       [ 85.   ,  26.6  ,  31.   ,   1.   ,   0.351,   0.   ],
       [183.   ,  23.3  ,  32.   ,   8.   ,   0.672,   0.   ],
       ...,
       [121.   ,  26.2  ,  30.   ,   5.   ,   0.245, 112.   ],
       [126.   ,  30.1  ,  47.   ,   1.   ,   0.349,   0.   ],
       [ 93.   ,  30.4  ,  23.   ,   1.   ,   0.315,   0.   ]])

In [14]:
y = df['Outcome'].values

In [15]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

# **Model Trainning**

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [18]:
x_test

array([[1.990e+02, 4.290e+01, 2.200e+01, 1.000e+00, 1.394e+00, 0.000e+00],
       [1.070e+02, 3.360e+01, 2.300e+01, 2.000e+00, 4.040e-01, 1.000e+02],
       [7.600e+01, 3.400e+01, 2.500e+01, 4.000e+00, 3.910e-01, 0.000e+00],
       [1.660e+02, 2.580e+01, 5.100e+01, 5.000e+00, 5.870e-01, 1.750e+02],
       [1.110e+02, 2.460e+01, 3.100e+01, 0.000e+00, 6.600e-01, 0.000e+00],
       [8.100e+01, 2.660e+01, 2.400e+01, 1.000e+00, 2.830e-01, 4.000e+01],
       [1.520e+02, 3.420e+01, 3.300e+01, 9.000e+00, 8.930e-01, 1.710e+02],
       [1.760e+02, 3.330e+01, 5.200e+01, 3.000e+00, 1.154e+00, 1.560e+02],
       [1.270e+02, 2.770e+01, 2.500e+01, 2.000e+00, 1.600e+00, 2.750e+02],
       [1.030e+02, 3.770e+01, 5.500e+01, 6.000e+00, 3.240e-01, 1.900e+02],
       [1.580e+02, 3.160e+01, 2.800e+01, 3.000e+00, 8.510e-01, 2.450e+02],
       [1.870e+02, 4.360e+01, 5.300e+01, 5.000e+00, 1.034e+00, 2.070e+02],
       [1.140e+02, 2.490e+01, 5.700e+01, 5.000e+00, 7.440e-01, 0.000e+00],
       [8.200e+01, 2.850e

# **Feature Scaling**

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
sc = StandardScaler()

In [21]:
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [22]:
x_test

array([[ 2.39507259e+00,  1.52657475e+00, -9.30642826e-01,
        -8.92954322e-01,  2.78935129e+00, -6.69261578e-01],
       [-4.25892449e-01,  3.19441160e-01, -8.35980346e-01,
        -5.65537738e-01, -2.76988247e-01,  2.80308009e-01],
       [-1.37643502e+00,  3.71360884e-01, -6.46655385e-01,
         8.92954322e-02, -3.17253311e-01, -6.69261578e-01],
       [ 1.38320470e+00, -6.92993461e-01,  1.81456910e+00,
         4.16712017e-01,  2.89819971e-01,  9.92485199e-01],
       [-3.03241795e-01, -8.48752633e-01, -7.86805031e-02,
        -1.22037091e+00,  5.15923795e-01, -6.69261578e-01],
       [-1.22312170e+00, -5.89154013e-01, -7.41317865e-01,
        -8.92954322e-01, -6.51763079e-01, -2.89433743e-01],
       [ 9.53927407e-01,  3.97320746e-01,  1.10644458e-01,
         1.72637836e+00,  1.23759765e+00,  9.54502416e-01],
       [ 1.68983133e+00,  2.80501367e-01,  1.90923158e+00,
        -2.38121153e-01,  2.04599625e+00,  8.12066978e-01],
       [ 1.87360820e-01, -4.46374771e-01, -6.466

# ***Logistic Regression***

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
classifier = LogisticRegression()

In [25]:
classifier.fit(x_train, y_train)

LogisticRegression()

In [26]:
pred_y = classifier.predict(x_test)

In [27]:
pred_y

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

# **Classification Metrics**

In [28]:
from sklearn.metrics import accuracy_score

In [29]:
accuracy_score(y_test, pred_y)

0.8246753246753247

In [30]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test, pred_y)

array([[96, 11],
       [16, 31]])

**Model Testing for Individual One**

In [31]:
classifier.predict(sc.transform([[226,35.5,35,1,0.627,90]]))

array([1])

In [32]:
classifier.predict(sc.transform([[106,20.5,28,1,0.127,86]]))

array([0])